import unittest
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
import os

class PythonOrgSearch(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Firefox()

    def test_search_in_python_org(self):
        driver = self.driver
        driver.get("http://ccapp-test.marpasoft.com/")
        self.assertIn("Welcom", driver.title)
        elem = driver.find_element_by_css_selector('a.btn.btn-primary.log-in')
        elem.click()
        username = driver.find_element_by_id('id_username')
        username.send_keys("zipppt@gmail.com")
        password = driver.find_element_by_id('id_password')
        password.send_keys("zipppt2016")
        log = driver.find_element_by_id('submit_button')
        log.click()
        RADTI = driver.find_element_by_xpath("//div[@class='row menu']/div[@class='col-sm-3'][2]/ul[3]/li[2]/a")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//div[@class='wrapit']/h4[1]/a")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-first_name']/input")
        RADTI.clear()
        RADTI.send_keys("Andrew")
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-last_name']/input")
        RADTI.clear()
        RADTI.send_keys("Trofimchuk")
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-middle_name']/input")
        RADTI.clear()
        RADTI.send_keys("Nikola")
        element = self.driver.find_element_by_id('id_personal_info-date_of_birth_month')
        select = Select(element)
        select.select_by_visible_text("July")
        element = self.driver.find_element_by_id('id_personal_info-date_of_birth_day')
        select = Select(element)
        select.select_by_visible_text("6")
        element = self.driver.find_element_by_id('id_personal_info-date_of_birth_year')
        select = Select(element)
        select.select_by_visible_text("1978")
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-ssn']/input")
        RADTI.clear()
        RADTI.send_keys("1111")
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-street']/input")
        RADTI.clear()
        RADTI.send_keys("Golosiivska St.")
        element = self.driver.find_element_by_id('id_personal_info-state')
        select = Select(element)
        select.select_by_visible_text("California")
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-city']/input")
        RADTI.clear()
        RADTI.send_keys("Sacramento")
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-zip']/input")
        RADTI.clear()
        RADTI.send_keys("00000")
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-phone']/input")
        RADTI.clear()
        RADTI.send_keys("000-000-0000")
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_personal_info-email']/input")
        RADTI.clear()
        RADTI.send_keys("zipppt@gmail.com")
        RADTI = driver.find_element_by_xpath("//div[@class='form_block']/a[1]/span")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//input[@id='id_agree']")
        #тут два кика захуярил, по ходу ниже тоже нужно в некоторых местах по два впиздячить
        RADTI.click()
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//a[@id='submit_button']/span")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//input[@id='id_agree']")
        RADTI.click()
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//a[@id='submit_button']/span")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//div[@id='div_id_registered']/input")
        RADTI.click()
        element = self.driver.find_element_by_id('id_initial_date_month')
        select = Select(element)
        select.select_by_visible_text("July")
        element = self.driver.find_element_by_id('id_initial_date_day')
        select = Select(element)
        select.select_by_visible_text("6")
        element = self.driver.find_element_by_id('id_initial_date_year')
        select = Select(element)
        select.select_by_visible_text("2015")
        RADTI = driver.find_element_by_xpath("//input[@id='id_current_organization_0']")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//input[@id='id_certified']")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//input[@id='id_have_ever_revoked_0']")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//a[@id='submit_button']/span")
        RADTI.click()
        RADTI = driver.find_element_by_xpath("//input[@id='id_type_0']")
        RADTI.click()
        #RADTI = driver.find_element_by_xpath("//a[@id='submit_button']/span")
        #RADTI.click()
        RADTI = driver.find_element_by_id("SWFUpload_0")
        RADTI.sendKeys("C:\\Users\\Андрей\\Downloads\\Новая папка\\IMAG0430.jpg")


    def tearDown(self):
        # self.driver.close()
        pass



if __name__ == "__main__":
    unittest.main()
