

from selenium.webdriver.support.ui import Select

def doForm(driver):

    element = driver.find_element_by_xpath("//div[@id='div_id_nominator_name']/input")
    element.clear()
    element.send_keys("Andrew Trofimchuk")
    element = driver.find_element_by_xpath("//div[@id='div_id_nominator_email']/input")
    element.clear()
    element.send_keys("zipppt@gmail.com")
    element = driver.find_element_by_xpath("//div[@id='div_id_nominator_phone']/input")
    element.clear()
    element.send_keys("222-222-2222")
    element = driver.find_element_by_xpath("//div[@id='div_id_name']/input")
    element.clear()
    element.send_keys("Andrew")
    element = driver.find_element_by_xpath("//div[@id='div_id_address']/input")
    element.clear()
    element.send_keys("Golosiivska St.")
    element = driver.find_element_by_xpath("//div[@id='div_id_city']/input")
    element.clear()
    element.send_keys("Sacramento")
    element = driver.find_element_by_id('id_state')
    select = Select(element)
    select.select_by_visible_text("California")
    element = driver.find_element_by_xpath("//div[@id='div_id_zip']/input")
    element.clear()
    element.send_keys("11111")
    element = driver.find_element_by_xpath("//div[@id='div_id_home_phone']/input")
    element.clear()
    element.send_keys("222-222-2222")
    element = driver.find_element_by_xpath("//div[@id='div_id_work_phone']/input")
    element.clear()
    element.send_keys("333-333-3333")
    element = driver.find_element_by_xpath("//div[@id='div_id_bio']/textarea")
    element.clear()
    element.send_keys("aaaaaaaaaaa")
